Judo/Judo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from Judo import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include(('backend.urls', 'backend'), namespace='backend')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Judo/api/urls.py
from rest_framework import routers
from django.urls import include, path

from .views import PhotoGalleryViewSet

router = routers.DefaultRouter()
router.register('photogalary', PhotoGalleryViewSet)

urlpatterns = [
    path('v1/', include(router.urls)),
]

Judo/backend/urls.py
from django.urls import path

from .views import (index, team, photo, shedule, add_page, login,
                    post_list, read_post, post_comment, gallery, gallery_edit,
                    add_photo, view_photo, delete_photo, download_file,
                    delete_category, news, add_news, price)
app_name = 'backend'

urlpatterns = [
    path('', index, name='home'),
    path('team/', team, name='team'),
    path('photo/', photo, name='photo'),
    path('shedule/', shedule, name='shedule'),
    path('price/', price, name='price'),
    path('post_list/', post_list, name='post_list'),
    path('login/', login, name='login'),
    path('post/<slug:post_slug>/', read_post, name='read_post'),
    path('add_page/', add_page, name='add_page'),
    path('<int:post_id>/comment/', post_comment, name='post_comment'),
    path('gallery', gallery, name='gallery'),
    path('gallery_edit', gallery_edit, name='gallery_edit'),
    path('delete_photo/<str:pk>/', delete_photo, name='delete_photo'),
    path('photo/<str:pk>/', view_photo, name='view_photo'),
    path('add/', add_photo, name='add'),
    path('news/', news, name='news'),
    path('download/<int:file_id>/', download_file, name='download_file'),
    path('category/<int:pk>/', delete_category, name='delete_category'),
    path('add_news/', add_news, name='add_news'),
]

Judo/backend/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['title', 'slug', 'content', 'photo', 'is_published']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }


class PhotoForm(forms.ModelForm):
    class Meta:
        model = PostsPhoto
        fields = ['photo']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (['body'])


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100,
        widget=forms.TextInput(
            attrs={'class': 'no-label', 'placeholder': 'Ваше имя'}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'no-label', 'placeholder': 'Ваш Email'}
        )
    )
    phone = forms.CharField(
        max_length=20,
        widget=forms.TextInput(
            attrs={'class': 'no-label', 'placeholder': 'Ваш телефон'}
        )
    )
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'no-label', 'placeholder': 'Сообщение'}
        )
    )


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError('Это поле обязательно для заполнения.')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if not content:
            raise forms.ValidationError('Это поле обязательно для заполнения.')
        return content

Judo/backend/views.py
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Case, When, Value, IntegerField
from datetime import datetime
from pytils.translit import slugify

from .models import *
from .models import Category, PhotoGallery, News, Schedule
from .models import File
from users.models import Profile
from .forms import AddPostForm, CommentForm, PhotoForm, ContactForm, NewsForm


menu = [
        {'title': "Новости", 'url_name': 'backend:post_list'},
        {'title': "Расписание", 'url_name': 'backend:shedule'},
        {'title': "Фотогалерея", 'url_name': 'backend:gallery'},
        {'title': "Стоимость", 'url_name': 'backend:price'},
        {'title': "О клубе", 'url_name': 'backend:team'},
        ]


def price(request):
    context = {
        'title': 'Стоимость',
    }
    return render(request, 'backend/price.html', context=context)


def download_file(request, file_id):
    file = get_object_or_404(File, id=file_id)
    response = HttpResponse(file.file, content_type='application/octet-stream')
    file_name = file.file.name.split('/')[-1]
    if file_name.isascii():
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
    else:
        file_name_name = file_name.split('.')[0]
        file_name_ext = file_name.split('.')[-1]
        file_name_name = slugify(file_name_name)
        file_name_ext = file_name_name + "." + file_name_ext
        response['Content-Disposition'] = f'attachment; filename="{file_name_ext}"'
    return response


def index(request):
    posts_list = Posts.objects.order_by('time_create') # [:2]
    paginator = Paginator(posts_list, 6)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    latest_news = News.objects.order_by('-pub_date').first()
    day_of_week = datetime.today().weekday()
    days = ['Понедельник', 'Вторник', 'Среда',
            'Четверг', 'Пятница', 'Суббота', 'Воскресенье']
    context = {
        'title': 'Главная страница',
        'posts': posts,
        'latest_news': latest_news,
    }
    print("Сегодняшний день недели:", days[day_of_week])
    schedules = Schedule.objects.filter(day=days[day_of_week])

    if schedules.exists():
        for schedule in schedules:
            message = f'Привет {request.user.username}, сегодня тренировка в {schedule.time} по адресу {schedule.address}' \
                if request.user.is_authenticated else 'Добро пожаловать!'
            messages.add_message(request, messages.INFO, message)
            context.update({
                'address': schedule.address,
                'time': schedule.time,
            })
    else:
        message = f'Привет {request.user.username}, сегодня нет тренировок! Можно отдохнуть.' \
            if request.user.is_authenticated else 'Добро пожаловать!'
        messages.add_message(request, messages.INFO, message)
    return render(request, 'backend/index.html', context=context)


def post_list(request):
    posts = Posts.objects.all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'menu': menu,
        'title': 'Новости',
    }
    return render(request, 'backend/posts.html', context=context)


def photo(request):
    form = PhotoForm(
            request.POST,
            files=request.FILES or None
        )
    photo = PostsPhoto.objects.all()
    paginator = Paginator(photo, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'backend/photo.html', {'menu': menu, 'title': 'Фотогалерея', 'page_obj': page_obj, 'form': form})


def team(request):
    context = {
        'menu': menu,
        'title': 'О клубе',
    }
    return render(request, 'backend/team.html', context=context)


def shedule(request):
    days_order = Case(
        When(day='Понедельник', then=Value(1)),
        When(day='Вторник', then=Value(2)),
        When(day='Среда', then=Value(3)),
        When(day='Четверг', then=Value(4)),
        When(day='Пятница', then=Value(5)),
        When(day='Суббота', then=Value(6)),
        When(day='Воскресенье', then=Value(7)),
        output_field=IntegerField(),
    )
    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        schedules = Schedule.objects.filter(age_group=profile.age_group).order_by(days_order)
    else:
        schedules = Schedule.objects.all().order_by('age_group', days_order)
    return render(request, 'backend/shedule.html', {'menu': menu,
                                                    'title': 'Расписание',
                                                    'schedules': schedules,})


def read_post(request, post_slug):
    post = get_object_or_404(Posts,
                             slug=post_slug)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'menu': menu,
        'title': post.title,
        'comments': comments,
        'form': form,
    }
    return render(request, 'backend/detail_post.html', context)


@login_required(login_url='backend:login')
def add_page(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('backend:home')

    else:
        form = AddPostForm()
    return render(request, 'backend/add_page.html', {'form': form, 'menu': menu, 'title': 'Добавление статьи'})


def login(request):
    return render(request, 'users/login.html')


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Posts,
                             id=post_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return render(request, 'backend/comment.html',
                            {'post': post,
                             'form': form,
                             'comment': comment})


def signup(request):
    return render(request, 'users/signup.html')


# @login_required(login_url='login')
def gallery(request):
    user = request.user
    category = request.GET.get('category')
    if category == None:
        photos = PhotoGallery.objects.all()
    else:
        photos = PhotoGallery.objects.filter(
            category__name=category)
    paginator = Paginator(photos, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'photos': photos,
        'menu': menu,
        'title': 'Фотоальбом',
        'page_obj': page_obj,
    }
    return render(request, 'backend/gallery.html', context)


def gallery_edit(request):
    user = request.user
    category = request.GET.get('category')
    if category == None:
        photos = PhotoGallery.objects.all()
    else:
        photos = PhotoGallery.objects.filter(
            category__name=category)
    paginator = Paginator(photos, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    categories = Category.objects.all()
    context = {'categories': categories, 'photos': photos, 'menu': menu, 'title': 'Фотоальбом', 'page_obj': page_obj}
    return render(request, 'backend/gallery_edit.html', context)


def view_photo(request, pk):
    photo = PhotoGallery.objects.get(id=pk)
    return render(request, 'backend/view_photo.html', {'menu': menu, 'photo': photo})


@login_required(login_url='backend:login')
def delete_photo(request, pk):
    photo_pk = PhotoGallery.objects.get(id=pk)
    photo_pk.delete()
    return redirect('backend:gallery_edit')


@login_required(login_url='login')
def add_photo(request):
    user = request.user
    categories = user.category_set.all()
    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')
        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                user=user,
                name=data['category_new'])
        else:
            category = None
        for image in images:
            photo = PhotoGallery.objects.create(
                category=category,
                image=image,
            )
        return redirect('backend:gallery')
    context = {'categories': categories}
    return render(request, 'backend/add.html', context)


def delete_category(request, pk):
    category = Category.objects.get(id=pk)
    PhotoGallery.objects.filter(category=category).delete()
    category.delete()
    return redirect('backend:gallery')


def news(request):
    news_list = News.objects.all()
    context = {'news_list': news_list,
               'menu': menu}
    return render(request, 'backend/news.html', context)


@login_required
@user_passes_test(lambda u: u.is_staff)
def add_news(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            latest_news = News.objects.latest('pub_date')
            latest_news.delete()
            news = form.save(commit=False)
            news.author = request.user
            news.save()
            messages.success(request, 'Новость успешно добавлена!')
            return redirect('backend:home')
    else:
        form = NewsForm()

Judo/templates/backend/add.html
{% extends 'base.html' %}

{% block content %}



<body class="">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <a href="{% url 'backend:gallery' %}" class="btn btn-dark my-3">Вернуться назад</a>
                <div class="card">
                    <form method='POST' action="" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group m-3">
                            <label>Выберите фотоальбом</label>
                            <select name="category" class="form-control">
                                <option value='none'>Выберите существующий фотоальбом</option>

                                {% for category in categories %}
                                <option value='{{category.id}}'>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group m-3">
                            <label>Создать новый фотоальбом</label>
                            <input name="category_new" type="text" placeholder="Название нового фотоальбома"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Загрузить</label>
                            <input required name="images" type="file" multiple class="form-control-file">
                        </div>

                        <button type='submit' class="btn btn-primary m-3">Загрузить</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock %}

Judo/templates/backend/add_news.html
{% extends 'base.html' %}

{% block content %}
<h2>Добавить новость</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-dark">Добавить новость</button>
</form>
{% endblock %}

Judo/templates/backend/add_page.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form action="{% url 'backend:add_page' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit" class="btn btn-dark btn-block btn-sm m-1">Добавить</button>
</form>

{% endblock %}

Judo/templates/backend/comment.html
{% extends 'base.html' %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Ваш комментарий добавлен.</h2>
    <p><a href="{{ post.get_absolute_url }}">Вернуться к постам</a></p>
  {% else %}
    <div class="comment-section">
      {% include 'includes/comment_form.html' %}
    </div>
  {% endif %}

{% endblock %}

<style>
  /* Стили для выравнивания по левому краю */
  .comment-section {
      text-align: left; /* Выравнивание по левому краю */
      max-width: 600px; /* Ограничение ширины для лучшего отображения */
      margin: 0 auto; /* Центрирование всего блока */
      padding: 20px;
  }
</style>

Judo/templates/backend/delete_photo.html
{% extends 'base.html' %}

{% block content %}

Delete!

{% endblock %}

Judo/templates/backend/detail_post.html
{% extends 'base.html' %}

<style>
  .published-date {
      text-align: right; /* Выравнивание текста по правому краю */
      color: #aaa; /* Бледно-серый цвет текста */
      margin-top: 10px; /* Отступ сверху для лучшего отображения */
  }
  .date-container {
      display: flex; /* Используем flexbox для выравнивания элементов */
      justify-content: space-between; /* Размещаем элементы по краям контейнера */
      align-items: center; /* Вертикальное выравнивание элементов */
  }
</style>

{% block content %}
    <div class="card-body">
        <h1 class="card-title text-center" style="color: black;">{{ post.title }}</h1>
        <div class="date-container"> <!-- Новый контейнер для даты и изображения -->


        <p class="card-text" style="font-size: 1.1em; line-height: 1.6;">{{ post.content|linebreaks }}</p>

                {% if post.photo %}
            <p class="text-center my-3"> <!-- Убираем лишние отступы, чтобы центрировать изображение -->
                <img class="img-fluid rounded post-image" src="{{ post.photo.url }}" alt="{{ post.title }}" style="width: 75%; max-width: 100%; height: auto;">
            </p>
        {% endif %}
        </div>

        <p class="article-date text-muted" style="font-size: 0.9em; margin: 5px 0; text-align: right; color: #aaa;">
            {{ post.time_update }}
        </p>

        <!-- Комментарии -->
        <div class="card-footer bg-light">
            <h3 class="text-secondary">Комментарии</h3>
            <div class="comments-section mt-4">
                {% for comment in comments %}
                    <div class="d-flex mb-4 p-3 border rounded bg-white shadow-sm">
                        <table style="width: 100%; border-collapse: collapse;">
                            <tr>
                                <td style="width: 50px; vertical-align: top; border: none;"> <!-- Аватар -->
                                    {% if comment.author.profile.avatar %}
                                        <img class="rounded-circle account-img" src="{{ comment.author.profile.avatar.url }}" alt="{{ comment.author.username }}" width="50" height="50">
                                    {% else %}
                                        <img class="rounded-circle account-img" src="path/to/default-avatar.jpg" alt="default avatar" width="50" height="50">
                                    {% endif %}
                                </td>
                                <td style="border: none;"> <!-- Имя пользователя и дата -->
                                    <h5 class="mt-0 font-weight-bold">{{ comment.author.username }}</h5>
                                    <small class="text-muted">{{ comment.created|date:"d M Y, H:i" }}</small>
                                    <p class="text-muted mt-1" style="font-size: 0.95em; line-height: 1.4;">{{ comment.body|linebreaks }}</p>
                                </td>
                            </tr>
                        </table>
                    </div>
                {% empty %}
                    <div class="alert alert-info" role="alert">
                        Пока нет комментариев.
                    </div>
                {% endfor %}
            </div>
        </div>

        {% if user.is_authenticated %}
            <div class="my-3">
                {% include 'includes/comment_form.html' %}
            </div>
        {% else %}
            <h4 class="text-warning">Зарегистрируйтесь, чтобы оставить комментарий!</h4>
        {% endif %}
    </div>
</div>

{% endblock %}

Judo/templates/backend/download_file.html
{% extends 'base.html' %}

{% block content %}
  <h1>Список файлов</h1>
  <ul>
    {% for file in files %}
      <li><a href="{% url 'download_file' file.id %}"></a></li>
    {% empty %}
      <li>Нет файлов.</li>
    {% endfor %}
  </ul>
{% endblock %}

Judo/templates/backend/gallery.html
{% extends 'base.html' %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.js"></script>

<style>
    .image-thumbail {
        height: 200px;
        width: 300px;
        object-fit: cover;

    }
    .list-group-item a {
        text-decoration: none;
        color: black;
    }
</style>

    {% if request.user.is_superuser %}
        <p align="right">
            <a href="{% url 'backend:gallery_edit' %}" class="btn btn-dark btn-block btn-sm m-1">Редактировать</a>
        </p>
    {% endif %}



<body class="">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if request.user.is_authenticated %}
                    <p>Привет {{request.user.username}}!</p>
                {% endif %}

                <div class="card">
                    <div class="card-header" style="display: flex; justify-content: space-between;">
                        Фотоальбомы

                    </div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'backend:gallery' %}">Все фото</a>
                        </li>

                        {% for category in categories %}
                        <li class=" list-group-item">
                            <a href="{% url 'backend:gallery' %}?category={{category.name}}">
                              <div style="display: flex; justify-content: space-between;">
                            {{category.name}}
                            </div>
                            </a>

                        {% endfor %}

                    </ul>
                </div>
                        {% if request.user.is_superuser %}
                            <a href="{% url 'backend:add' %}" class="btn btn-dark btn-block btn-sm m-1">Добавить фото</a>
                        {% endif %}


            </div>
    <div class="col-md-9">
        <div class="row">

            {% for photo in page_obj %}
            <div class="col-md-4">
                <div class="card my-2">
                  <a href="{{ photo.image.url }}" data-fancybox="gallery">
                        <img class="image-thumbail" src="{{photo.image.url}}" alt="Card image cap" >
                    </a>

                </div>
            </div>

            {% empty %}
            <h3>No photos...</h3>
            {% endfor %}

        </div>
    </div>
        </div>
    </div>

</body>
{% include 'includes/paginator.html' %}
{% endblock %}

Judo/templates/backend/gallery_edit.html
{% extends 'base.html' %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.js"></script>

<style>
    .image-thumbail {
        height: 200px;
        width: 300px;
        object-fit: cover;

    }
    .list-group-item a {
        text-decoration: none;
        color: black;
    }
</style>

        {% if request.user.is_superuser %}
            <p align="right">
                <a href="{% url 'backend:gallery' %}" class="btn btn-dark btn-block btn-sm m-1">Закрыть редактирование</a>
            </p>
        {% endif %}



<body class="">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if request.user.is_authenticated %}
                    <p>Привет {{request.user}}!</p>
                {% endif %}

                <div class="card">
                    <div class="card-header" style="display: flex; justify-content: space-between;">
                        Фотоальбомы

                    </div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'backend:gallery' %}">Все фото</a>
                        </li>

                        {% for category in categories %}
                        <li class=" list-group-item">
                            <a href="{% url 'backend:gallery' %}?category={{category.name}}">
                              <div style="display: flex; justify-content: space-between;">
                            {{category.name}}
                        {% if request.user.is_superuser %}

                            <form action="{% url 'backend:delete_category' category.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-outline-dark btn-sm m-0" type="">Удалить</button>
                            </form>
                          {% endif %}
                            </div>
                            </a>

                        {% endfor %}

                    </ul>
                </div>
                        {% if request.user.is_superuser %}
                            <a href="{% url 'backend:add' %}" class="btn btn-dark btn-block btn-sm m-1">Добавить фото</a>
                        {% endif %}


            </div>
    <div class="col-md-9">
        <div class="row">

            {% for photo in page_obj %}
            <div class="col-md-4">
                <div class="card my-2">
                  <a href="{{ photo.image.url }}" data-fancybox="gallery">
                        <img class="image-thumbail" src="{{photo.image.url}}" alt="Card image cap" >
                    </a>
                    {% if request.user.is_superuser %}
                        <a href="{% url 'backend:delete_photo' photo.id %}" class="btn btn-outline-dark btn-sm m-1">delete</a>
                    {% endif %}

                </div>
            </div>

            {% empty %}
            <h3>No photos...</h3>
            {% endfor %}

        </div>
    </div>
        </div>
    </div>

</body>
{% include 'includes/paginator.html' %}
{% endblock %}

Judo/templates/backend/posts.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<style>
    .article-list {
        list-style-type: none;
        padding: 0;
    }
    .article-item {
        background-color: #f8f9fa;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .article-title {
        font-size: 1.5em;
        color: #343a40;
        margin-top: 0;
    }
    .article-content {
        color: #495057;
    }
    .article-image {
        max-width: 100px;
        float: left;
        margin-right: 15px;
        border-radius: 4px;
    }
    .read-more {
        display: inline-block;
        margin-top: 10px;
    }
</style>

<style>
  /* Стили для ссылки заголовка */
  .article-title a {
      text-decoration: none; /* Убираем подчеркивание */
      color: inherit; /* Цвет текста наследуется от родителя */
  }

  .article-title a:hover {
      text-decoration: none; /* Убираем подчеркивание при наведении */
      color: inherit; /* Оставляем цвет таким же при наведении */
  }
</style>

<ul class="article-list">
    {% for p in page_obj %}
    <li class="article-item">
        {% if p.photo %}
            <img class="article-image" src="{{ p.photo.url }}" alt="{{ p.title }}">
        {% endif %}

        <!-- Заголовок с ссылкой -->
        <h2 class="article-title">
            <a href="{{ p.get_absolute_url }}" class="read-more">
                {{ p.title }}
            </a>
        </h2>

        <p class="article-content">{{ p.content|linebreaks|truncatewords:50 }}</p>
        <div class="clear"></div>

        <!-- Отображение даты -->
        <p class="article-date text-muted" style="font-size: 0.9em; margin: 5px 0;">
            Опубликовано: {{ p.time_create|date:"d M Y" }}
        </p>

        <!-- Кнопка "Читать запись" -->
        <p style="text-align: right;">
            <a href="{{ p.get_absolute_url }}" class="read-more">
                <button type="button" class="btn btn-outline-dark btn-sm">Читать запись</button>
            </a>
        </p>
    </li>
    {% endfor %}

    {% include 'includes/paginator.html' %}
</ul>

{% endblock %}

Judo/templates/backend/view_photo.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <div class="container">
    <a href="{% url 'backend:view_photo' photo.id|add:-1 %}">← Предыдущее фотор</a>
    <div style="display: flex; justify-content: flex-end;">
        <a href="{% url 'backend:view_photo' photo.id|add:1 %}">Следующее фотор →</a>

        </div>

<p style="text-align: center;">{{ photo.description|center:50 }}</p>
        <div class="row justify-content-center">
            <div class="col">



                <div style="height: 90vh;">
                <div style="display: flex; justify-content: center;">

                    <img src="{{ photo.image.url }}" alt="{{ photo.title }}" style="max-width: 600px; max-height: 600px;">


                </div>
    {% if not is_last_photo %}
        <a href="{% url 'backend:view_photo' photo.id|add:1 %}">Следующее фотор →</a>
    {% endif %}

            </div>
        </div>
    </div>

</body>

{% endblock %}