Judo/Judo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from Judo import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include(('backend.urls', 'backend'), namespace='backend')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Judo/api/urls.py
from rest_framework import routers
from django.urls import include, path

from .views import PhotoGalleryViewSet

router = routers.DefaultRouter()
router.register('photogalary', PhotoGalleryViewSet)

urlpatterns = [
    path('v1/', include(router.urls)),
]

Judo/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.views.generic import TemplateView

from . import views
from .views import EmailVerify, profile, my_login_view


app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(),
         name='signup'),
    # path('login/',
    #      LoginView.as_view(template_name='users/login.html'),
    #      name='login'),

    path(
        'invalid_verify/',
        TemplateView.as_view(template_name='users/invalid_verify.html'),
        name='invalid_verify'
    ),

    path(
        'verify_email/<uidb64>/<token>/',
        EmailVerify.as_view(),
        name='verify_email',
    ),

    path(
        'confirm_email/',
        TemplateView.as_view(template_name='users/confirm_email.html'),
        name='confirm_email'
    ),


    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset_form'
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'
         ),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
    path('profile/', profile, name='profile'),
    path('login/', my_login_view, name='login'),
]

Judo/users/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from PIL import Image


class AgeGroup(models.Model):
    name = models.CharField(max_length=100, verbose_name="Возраст")
    
    class Meta:
        verbose_name = 'Возраст'
        verbose_name_plural = 'Возраст'
    
    def __str__(self):
        return self.name

    
class User(AbstractUser):
    email = models.EmailField(
        _('email address'),
        unique=True,
    )
    email_verify = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='ava2.png', upload_to='profile_images')
    bio = models.TextField()
    age_group = models.ForeignKey(AgeGroup, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)
        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

Judo/users/forms.py
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm,
    AuthenticationForm as DjangoAuthenticationForm,
)
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .utils import send_email_for_verify
from .models import Profile, AgeGroup

User = get_user_model()


class AuthenticationForm(DjangoAuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username is not None and password:
            self.user_cache = authenticate(
                self.request,
                username=username,
                password=password,
            )
            if not self.user_cache.email_verify:
                send_email_for_verify(self.request, self.user_cache)
                raise ValidationError(
                    'Email not verify, check your email',
                    code='invalid_login',
                )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data


class UserCreationForm(DjangoUserCreationForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = ("username", "email")


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    age_group = forms.ModelChoiceField(queryset=AgeGroup.objects.all())

    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'age_group']

Judo/users/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.views import LoginView
from django.core.exceptions import ValidationError
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.tokens import default_token_generator as \
    token_generator
from django.contrib.auth.decorators import login_required
from .forms import UserCreationForm
from .forms import AuthenticationForm
from .forms import UpdateProfileForm, UpdateUserForm
from backend.views import menu
from backend.models import *
from django.contrib import messages
from .models import Profile

from .utils import send_email_for_verify


from django.urls import reverse_lazy
from django.views.generic import CreateView

User = get_user_model()


def my_login_view(request, *args, **kwargs):
    view = LoginView.as_view(template_name='users/login.html', extra_context={'menu': menu})
    return view(request, *args, **kwargs)


class EmailVerify(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('backend:home')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


class SignUp(CreateView):
    template_name = 'users/signup.html'

    def get(self, request):
        context = {
            'menu': menu,
            'form': UserCreationForm(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email_for_verify(request, user)
            return redirect('users:confirm_email')
        context = {
            'menu': menu,
            'form': form,
        }
        return render(request, self.template_name, context)


@login_required
def profile(request):
    user = request.user
    if not hasattr(user, 'profile'):
        Profile.objects.create(user=user)
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
    
    return render(request, 'users/profile.html', {'menu': menu,
                                                  'user_form': user_form,
                                                  'profile_form': profile_form,})

Judo/templates/users/confirm_email.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <p>Пожалуйста проверьте свою почту чтобы завершить регистрацию.</p>
    </div>
{% endblock %}

Judo/templates/users/invalid_verify.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <p>Ваша ссылка не корректна, залогиньтесь снова</p>
        <a href="{% url 'login' %}">Залогиниться</a>
    </div>
{% endblock %}

Judo/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

Judo/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock title %}
{% block content %}
<!--{% load user_filters %}-->

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}

          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    <a href="{% url 'users:login' %}" class="text-white text-decoration-none">
                        Войти
                    </a>
                </button>

            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

Judo/templates/users/password_change_done.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">  
    <title>Пароль изменён</title>
  </head>
  <body>	   
    <header>
      <header>

      </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2025 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>
</html>

Judo/templates/users/password_change_form.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">  
    <title>Изменение пароля</title>
  </head>
  <body>	   
    <header>

    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

Judo/templates/users/password_reset_complete.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">  
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>	   
    <header>

    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

Judo/templates/users/password_reset_done.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">  
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:rgb(216, 111, 5)">J</span>udo</p>    
    </footer>
  </body>
</html>

Judo/templates/users/password_reset_form.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru"> 
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">   
    <title>Сброс пароля</title>
  </head>
  <body>	   
    <header>

    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="{% url 'users:password_reset_form' %}">
                  {% csrf_token %}
                  
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2023 Copyright <span style="color:red">J</span>udo</p>    
    </footer>
  </body>
</html>

Judo/templates/users/profile.html
{% extends "base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
<h1>Страница пользователя</h1>
    <div style="max-width: 600px; margin-left: 0; padding-left: 0;">
        <!-- Карточка с формой, выровнена влево -->
        <div class="card shadow-sm" style="text-align: left;">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data" class="text-start">
                    {% csrf_token %}

                    <!-- Аватарка пользователя в форме, выровнена влево -->
                    <div class="mb-4">
                        <img class="rounded-circle account-img shadow" src="{{ user.profile.avatar.url }}"
                             alt="User Avatar" style="width: 75px; height: 75px; object-fit: cover; cursor: pointer;">
                    </div>

                    <!-- Поля формы, выровнены влево -->
                    <div class="mb-3">
                        <label class="form-label">Имя:</label>
                        {{ user_form.username }}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Email:</label>
                        {{ user_form.email }}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Группа:</label>
                        {{ profile_form.age_group }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Сменить аватар:</label>
                        <!-- Скрываем стандартный элемент загрузки файла -->

                            <input type="file" id="avatarUpload" name="avatar" class="form-control d-none">
                            <label for="avatarUpload" class="btn btn-outline-secondary">
                                Выберите файл
                            </label>

                    </div>

                    <div class="mb-3">
                        <label class="form-label">О себе:</label>
                        {{ profile_form.bio }}
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'users:password_change_form' %}" class="text-decoration-none">Изменить пароль</a>
                    </div>

                    <!-- Кнопки формы -->
                    <div class="d-flex justify-content-start mt-4">
                        <button type="submit" class="btn btn-success me-2">Сохранить изменения</button>
                        <button type="reset" class="btn btn-outline-secondary">Сброс</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

Judo/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}

{% block title %}
Зарегистрироваться
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% if form.errors %}
                {% for field in form %} 
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small 
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

Judo/templates/users/verify_email.html
{% autoescape off %}

Hi {{ user.get_username }},
Пожалуйста перейдите по ссылке чтобы закончить регистрацию
http://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}

{% endautoescape %}